# This is a basic workflow to help you get started with Actions

name: Deploy to EC2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
        
      - name: Build docker image
        run: docker build . -t vui-forms/sample-api:latest
      
      - name: Save image to tar
        run: docker save vui-forms/sample-api:latest > vui-forms_sample-api.tar
      
      - name: Saving key string into file
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: touch key.pem && echo "$SSH_KEY" >> key.pem && chmod 400 key.pem
      
      - name: Send image using ftp
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: scp -i key.pem vui-forms_sample-api.tar "$SSH_USERNAME"@"$SSH_HOST":/home/ubuntu

      # SSH to specific AWS EC2 set on secrets
      - name: SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker --version
            ls -la
